// Code generated by "stringer -type=RemoveReason"; DO NOT EDIT.

package cache

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Expired-0]
	_ = x[NoSpace-1]
	_ = x[Deleted-2]
	_ = x[Clear-3]
}

const _RemoveReason_name = "ExpiredNoSpaceDeletedClear"

var _RemoveReason_index = [...]uint8{0, 7, 14, 21, 26}

func (i RemoveReason) String() string {
	if i >= RemoveReason(len(_RemoveReason_index)-1) {
		return "RemoveReason(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _RemoveReason_name[_RemoveReason_index[i]:_RemoveReason_index[i+1]]
}
